trigger:
  branches:
    include:
    - track2

pr:
  branches:
    include:
    - track2

variables:
  NodeVersion: '14.x'
  goTestPath: '$(system.defaultWorkingDirectory)/test'
  go.version: '1.17'
  GOBIN: '$(system.defaultWorkingDirectory)/bin/go'
  BlobFeedUrl: https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json
  OfficialBuildId: $(Build.BuildNumber)

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-for-go
      type: github
      name: Azure/azure-sdk-for-go
      endpoint: azure

stages:
  - stage: 'Generate_SDK'
    jobs:
      - job: Build_autorest_go
        pool:
          vmImage: ubuntu-20.04
        steps:
          - task: NodeTool@0
            displayName: 'Install Node $(NodeVersion)'
            inputs:
              versionSpec: '$(NodeVersion)'

          - checkout: self

          - script: |
              cd $(Agent.BuildDirectory)/s/autorest.go
              npm install -g "@microsoft/rush"
              rush update --debug
              npm install -g autorest
              rush rebuild -v
            displayName: 'Build autorest.go'
