trigger:
  branches:
    include:
    - track2

pr:
  branches:
    include:
    - track2

variables:
  NodeVersion: '14.x'
  goTestPath: '$(system.defaultWorkingDirectory)/test'
  go.version: '1.17'
  GOBIN: '$(system.defaultWorkingDirectory)/bin/go'
  BlobFeedUrl: https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json
  OfficialBuildId: $(Build.BuildNumber)

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-for-go
      type: github
      name: Azure/azure-sdk-for-go
      endpoint: azure

stages:
  - stage: 'Generate_SDK'
    jobs:
      - job: Build_autorest_go
        pool:
          vmImage: ubuntu-20.04
        steps:
          - task: NodeTool@0
            displayName: 'Install Node $(NodeVersion)'
            inputs:
              versionSpec: '$(NodeVersion)'

          - checkout: self

          - script: |
              cd $(Agent.BuildDirectory)/s/autorest.go
              npm install -g "@microsoft/rush"
              rush update --debug
              npm install -g autorest
              rush rebuild -v
            displayName: 'Build autorest.go'

          - checkout: azure-sdk-for-go
          - checkout: azure-sdk-tools
          - pwsh: ./build.ps1 -cleanGenerated -generate -goExtension=$(Agent.BuildDirectory)/s/autorest.go
            failOnStderr: true
            workingDirectory: $(Agent.BuildDirectory)/s/azure-sdk-for-go/eng/scripts
            displayName: 'Generate code in Azure SDK repo'

          # TODO: this step should open a PR in Azure/azure-sdk-for-go, maybe test it on the fork first ;-)
          # - template: /eng/common/pipelines/templates/steps/create-pull-request.yml@azure-sdk-tools
          #   parameters:
          #     BaseBranchName: main
          #     RepoName: azure-sdk-for-go
          #     PRBranchName: auto-update-autorest
          #     CommitMsg: Update autorest.go version to $(AutorestGoVersion)
          #     PRBody: Update autorest.go version to $(AutorestGoVersion)
          #     PRTitle:  Update autorest.go version
          #     PushArgs: -f
          #     WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-go
          #     ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts
